name: Bug Report
description: Issue form version for bug reports.
title: '[BUG] '
labels: ["bug"]
assignees: ["AssassinBear23"]
body:
  - type: markdown
    attributes:
      value: | 
        Thanks for taking the time to fill out this bug report! Please provide as much information as you can to help us understand and resolve the issue.
        Try to fill in as much detail as possible, however if certain fields are not applicable, feel free to write 'N/A'.
  - type: checkboxes
    id: existing_issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues and there is no existing issue for this bug.
        required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the bug in detail.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Please provide the steps to reproduce the bug.
        If not applicable, please write 'N/A'.
      placeholder: | 
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Please describe what you expected to happen.
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, please add screenshots to help explain your problem. If not applicable, please write 'N/A'.
      placeholder: Paste your screenshots here.
    validations:
      required: false
